spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flight
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
server:
  error:
    include-stacktrace: never
    include-message: ALWAYS
